module.exports = [
    {name: "bicycles"},
    {name: "mountain bikes"},
    {name: "computers"},
    {name: "piano"},
    {name: "french"},
    {name: "triathlon"},
    {name: "programming"},
    {name: "android"},
    {name: "wifi"},
    {name: "toyota"},
    {name: "mechanic"},
    {name: "ketogenic diet"},
    {name: "spanish"},
    {name: "airsoft"},
    {name: "cooking"},
    {name: "composting"},
    {name: "mandarin"},
    {name: "swimming"},
    {name: "rock climbing"},
    {name: "mathematics"},
    {name: "chemistry"},
    {name: "git"},
    {name: "accounting"},
    {name: "gulp"},
    {name: "reactjs"},
    {name: "aeron chairs"},
    {name: "dell xps15"},
    {name: "mantiz venus egpu"},
    {name: "essay writing"},
    {name: "mandrain"},
];